Further tweak fab-investigate.

diff --git a/bin/fab-investigate b/bin/fab-investigate
--- a/bin/fab-investigate
+++ b/bin/fab-investigate
@@ -1,14 +1,43 @@
 #!/bin/bash -eu
 
-target=$1
+usage() {
+    cat <<EOF
+Syntax:
 
-cp '/turnkey/fab/common/overlays/turnkey.d/systemd-chroot/usr/local/bin/service' "$target/usr/local/bin/service" || true
+    $(basename $0) path/to/chroot
+
+EOF
+    exit $1
+}
+
+[[ -n "$FAB_PATH" ]] || FAB_PATH="/turnkey/fab"
+
+if [[ $# -ne 1 ]]; then
+    echo "Error: Must provide path to chroot"
+    usage 1
+fi
+
+if [[ "$PWD" == "$FAB_PATH/products/"* ]]; then
+    app_name=$(basename $PWD)
+    # shorten app_name by removing first dash and everything after
+    app_name=${app_name%%-*}
+else
+    app_name="random"
+fi
+target=$1
+service=usr/local/bin/service
+
+cp "$FAB_PATH/common/overlays/turnkey.d/systemd-chroot/$service" "$target/$service" || true
 
 # disable confconsole from starting
-chmod -x "$target/root/.bashrc.d/confconsole-auto"
+chmod -x "$target/root/.bashrc.d/confconsole-auto" || true
+
+# make prompt show that we're in a chroot
+echo "$app_name chroot" > "$target/etc/debian_chroot"
 
 fab-chroot $target
 
 # after running undo what was done
-rm -rf "$target/usr/local/bin/service"
-chmod +x "$target/root/.bashrc.d/confconsole-auto"
+rm -rf "$target/$service"
+chmod +x "$target/root/.bashrc.d/confconsole-auto" || true
+rm -rf "$target/etc/debian_chroot"
