Vast improvements to tkldev-check-plan (old code made me cringe...).

diff --git a/bin/tkldev-check-plan b/bin/tkldev-check-plan
--- a/bin/tkldev-check-plan
+++ b/bin/tkldev-check-plan
@@ -1,88 +1,114 @@
-#!/bin/bash -e
+#!/bin/bash -eu
 # script to check a plan (or plans) to see if the packages are avaiable
 
 # accepts path to plan; defaults to plan/main
 
-if [ -z $1 ]; then
-    PLAN="plan/main"
+_RELEASE="$(lsb_release -si | tr [A-Z] [a-z])/$(lsb_release -sc)"
+RELEASE=${RELEASE:-$_RELEASE}
+DEBUG=${DEBUG:-}
+FAB_PATH=${FAB_PATH:-/turnkey/fab}
+
+fatal() { echo "FATAL: $@"; exit 1; }
+
+usage() {
+    cat <<EOF
+$(basename $0) [-a] [-u] [-x] [<path(s)>]
+
+Tool to process plan(s) and check that packages are available.
+
+By default it will check plan/main (i.e. assumes that you are in
+products/<appliance>). It will automatically pull in includes (e.g. common
+plans).
+
+Available packages are listed in alphabetical order, including version (to
+stdout) in the format:
+
+    pkg_name=version
+
+All packages noted but not available will be output (to stderr by default)
+in the format:
+
+    pkg_name=NOT_AVAILABLE
+
+Options:
+
+    -a|--all        - Check all plans found in
+                      /turnkey/fab/{common/plans/,products/*/plan/main}
+    -n|--no-update  - Don't run apt update prior to checking for packages
+    -o|--stdout     - Only output to stdout (even missing packages)
+
+Encironment:
+
+    DEBUG=y         Debug mode
+    RELEASE         Release to search packages for. If not set, defaults to
+                    host system ($_RELEASE).
+    FAB_PATH        Path for fab. Defaults to /turnkey/fab.
+EOF
+}
+
+[[ -z "$DEBUG" ]] || set -x
+
+ALL=""
+UPDATE="apt-get update -qq"
+ERROR='>&2'
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -a|--all)
+            ALL=y
+            shift;;
+        -n|--no-update)
+            UPDATE=""
+            shift;;
+        -o|--stdout)
+            ERROR=""
+            shift;;
+        *)
+            echo "Unknown imput $1"
+            usage;;
+    esac
+done
+
+if [[ -n "$ALL" ]]; then
+    PLANS=$(find $FAB_PATH/products/*/plan/ -type f)
+    COM_PLANS=$(find $FAB_PATH/common/plans/ -type f)
 else
-    unset PLAN
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            -a) PLAN="$(find /turnkey/fab/products /turnkey/fab/common -maxdepth 4 -type f -path '*/plan*')"
-                break
-                ;;
-            -u) apt-get update;;
-            -x) set -x;;
-	        --)	shift; break;;
-	        -*)
-                echo >&2 "usage:";
-                echo >&2 \
-                "       $(basename $0) [-a] [-u] [-x] [<path(s)>]"
-                echo >&2; echo >&2 \
-                "   <none>  check plan/main (assumes that you are in products/<appliance>)"
-                echo >&2 \
-                "       -a  check all plans from /turnkey/fab/{common,products}" 
-                echo >&2 \
-                "       -u  update package lists ('apt-get udpate')"
-                echo >&2 \
-                "       -x  debug mode"
-                echo >&2 \
-                "<path(s)>  file(s) &/or directory(ies) to process (full or relative path)"
-                echo >&2; echo >&2 \
-                "   FILES: all files are processed as if they are a plan"
-                echo >&2; echo >&2 \
-                "   DIRS: path or filename must include "plan" to be included"
-                echo >&2 \
-                "       only files within a directory will be included"
-                echo >&2 \
-                "               (sub dirs are not processed)"
+    [[ -f plan/main ]] || fatal "plan/main not found."
+    PLANS="$PWD/plan/main"
+    COM_PLANS=""
+fi
 
-		        exit 1;;
-        	*)	break;;		# terminate while loop
-        esac
-    shift
+packages=""
+
+for plan in $PLANS; do
+    this_plan=$(fab-plan-resolve $plan -I $FAB_PATH/common/plans \
+        | sed 's|\s.*$||')
+    packages="$packages $this_plan"
+done
+
+if [[ -n "$COM_PLANS" ]]; then
+    for plan in $COM_PLANS; do
+        this_plan=$(fab-plan-resolve $plan -I $FAB_PATH/common/plans \
+             | sed 's|\s.*$||')
+        packages="$packages $this_plan"
     done
 fi
 
-if [ -z "$PLAN" ]; then
-    while [ $# -gt 0 ]; do
-        if [ -f "$1" ]; then
-            echo "plan start: $PLAN"
-            PLAN="$PLAN"$'\n'"$1"
-            echo "plan finish: $PLAN"
-        else
-            FILES="$(find $(readlink -f $1) -maxdepth 1 -type f | grep plan)"
-            PLAN="$PLANi"$'\n'"$FILES"
-        fi
-	shift
-    done
-	[ -z "$PLAN" ] && echo "No valid plans" && exit 1
-fi
+packages=$(echo $packages | tr ' ' '\n' | sort -u)
 
-# sed stuff for reference
-# '/#/d' - remove every line which contains the '#' character
-# 's/\s.*$//' - remove everything after a space
-# '/^\s*$/d'- remove blank lines (inc lines with whitespace)
-
-#PLAN="$(echo "$PLAN" | tr " " "\n")"
-echo "plan: $PLAN"
-unset PKGS
-while read LINE; do
-    echo "line: $LINE"
-    unset BROKEN
-    if [ ! -z $LINE ]; then
-        PKGS="$(cat $LINE | sed  '/#/d' | sed 's/\/\*.*$//' | sed '/^\s*$/d')"
-        echo "pkgs: $PKGS"
-        PATTERN="E:"
-        BROKEN="$(apt-get install -s $PKGS 2>&1 | grep "$PATTERN" | sed "s/$PATTERN //")"
-        echo "broken: $BROKEN :broken"
-    if [ ! -z "$BROKEN" ]; then
-        echo "## From $LINE these packages have issues:"
-        echo "$BROKEN"
+$UPDATE
+pkg_avail=""
+not_avail=""
+for pkg in $packages; do
+    ver=$(apt-cache policy $pkg \
+            | grep Candidate: | sed "s|^.*Candidate: ||")
+    if [[ "$ver" =~ "none" ]]; then
+        not_avail="$not_avail $pkg=NOT_FOUND"
+    else
+        pkg_avail="$pkg_avail $pkg=$ver"
     fi
-done <<<"$PLAN"
+done
 
-echo "####"
-echo "Done"
-
+echo $pkg_avail | tr ' ' '\n'
+if [[ -n "$not_avail" ]]; then
+    echo $not_avail | tr ' ' '\n' $ERROR
+fi
